spring:
  #  profiles:
  #    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/lin-finance-local?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

# 日志配置
logging:
  file:
    name: ../${spring.application.name}/logs/lin-finance-admin-api.log